environment:
  global:
      PYTHON: "C:\\conda"
      CONDA_DEPENDENCIES: "nose setuptools flake8 coverage chardet"
      PIP_DEPENDENCIES: "codecov"
  matrix:
      - PYTHON_VERSION: "2.7"
        PYTHON_ARCH: "32"
  matrix:
      - PYTHON_VERSION: "3.6"
        PYTHON_ARCH: "64"

install:
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  - "python setup.py develop"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "flake8"
  - "nosetests"

on_success:
  - "codecov"
