# GitHub Action to check our dictionary, this should only be used by the codespell project itself
# For general usage in your repo, see the example in codespell.yml
# https://github.com/codespell-project/codespell
name: codespell
on: [push, pull_request]
jobs:
  make-check-dictionaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make check-dictionaries

  flake8-annotation:
    runs-on: ubuntu-latest
    steps:
      - name: Flake8 with annotations
        uses: TrueBrain/actions-flake8@v1.2
